### ISSUE TITLE
The formula is broken on Debian

### ISSUE THREAD

**Issue by n-rodriguez** [saltstack-formulas/vim-formula#33]
Hi! When running the `vim` state, this error happens:

```
          ID: /etc/vim/vimrc
    Function: file.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1843, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 2313, in managed
                  **kwargs
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 4407, in check_managed_changes
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3901, in get_managed
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 167, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 431, in render_jinja_tmpl
                  buf=tmplstr)
              SaltRenderError: Jinja variable 'str object' has no attribute 'get'
     Started: 01:49:39.019781
    Duration: 305.084 ms
     Changes:   
```

**Comment by n-rodriguez** [comment]
Thank you!
